### ISSUE TITLE
fix: Reduce the space between each row of cards

### ISSUE THREAD

**Issue by baekusboo** [baekusboo/music-website#100]
**Describe the bug**
The space between each row of the cards are more.

**To Reproduce**
1. Go to '[Music World Webpage](https://music-website-jade.vercel.app/)'
2. Scroll down

**Expected behavior**
Space between each row of the cards should be reduced and kept minimum.

**Screenshots**
<img width="947" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/1c183165-0773-4d5a-80a2-04b9cea6ab5c">

**Comment by real-coder007Ravi** [comment]
@baekusboo Could you please assign it to me

**Comment by Tanush-J** [comment]
I can work on this if nobody is working on this

**Comment by baekusboo** [comment]
@Tanush-J Do contribute! Don't forget to link this issue number when raising the PR.

**Comment by baekusboo** [comment]
@real-coder007Ravi As I have assigned other issues to you, I am assigning this issue to others. Thanks for your valuable contributions to this project!
