### ISSUE TITLE
fix: Align like button and suggested by text in the cards

### ISSUE THREAD

**Issue by baekusboo** [baekusboo/music-website#101]
**Describe the bug**
The contributor's name and the like button are not aligned properly in the same line. When the name is too long, the position of the like button is changed.

**To Reproduce**
1. Go to '[Music World Webpage](https://music-website-jade.vercel.app/)'
2. Scroll down
3. Observe the card UI

**Expected behavior**
The contributor's name and the like button should be aligned properly in the same line. For each card, fix the position of the like button at left with required margin and padding. It would be better to align the "suggested by NAME" left. Any unique idea will be appreciated to fix this issue.

**Screenshots**

<img width="879" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/54d8dc2f-05d1-4be8-acec-9723dd4aa907">

**Comment by real-coder007Ravi** [comment]
@baekusboo Could you please assign it to me.

**Comment by baekusboo** [comment]
Thanks for contributing to this issue! 

Happy Hacking! ^^

**Comment by Shubhguptacoder** [comment]
pls assign this issue to me
