### ISSUE TITLE
fix: Remove duplicate cards

### ISSUE THREAD

**Issue by baekusboo** [baekusboo/music-website#102]
**Describe the bug**
Duplicate cards are present.

**Expected behavior**
No cards should be repeated. Duplicates should be removed.

**Screenshots**
<img width="945" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/0c3fa04b-30d5-4183-9a06-ccddfd562722">

**Comment by real-coder007Ravi** [comment]
@baekusboo Could you please assign it to me

**Comment by baekusboo** [comment]
@real-coder007Ravi You can work on this issue, thanks for contributing!

**Comment by real-coder007Ravi** [comment]
@baekusboo issue #138
