### ISSUE TITLE
fix: Change suggested by text colour in dark mode

### ISSUE THREAD

**Issue by baekusboo** [baekusboo/music-website#103]
**Describe the bug**
Suggested by text is light colored in light bg. Text color is white. Thus the text is not visible in dark mode.

**To Reproduce**
1. Go to '[Music World Webpage](https://music-website-jade.vercel.app/)'
2. Change theme to dark
3. Observe the text in the cards

**Expected behavior**
Suggested by text color should be changed, such that it's visible in dark mode also.

**Screenshots**
<img width="436" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/30672310-0142-482f-9938-2d18039582f8">

**Comment by AnsellMaximilian** [comment]
Hey, @baekusboo. I can take this if that's okay.

**Comment by real-coder007Ravi** [comment]
Hey, @baekusboo. I want to work on this issue. Could you please assign it to me

**Comment by baekusboo** [comment]
Hey @AnsellMaximilian , you can proceed with this issue. Thanks for contributing!

Don't forget to link this issue number in your PR.

**Comment by Harsha19-08** [comment]
can u assign and see the preview of my previous pull request

**Comment by baekusboo** [comment]
@Harsha19-08  assigned you this issue, kindly raise the PR for the same, don't forget to link the issue!
