### ISSUE TITLE
fix: Like button colour should be changed for dark mode

### ISSUE THREAD

**Issue by baekusboo** [baekusboo/music-website#104]
**Describe the bug**

In dark mode, Like button colour is light colored. Color is grey. Thus the button/icon is not visible in dark mode.

**To Reproduce**

1. Go to '[Music World Webpage](https://music-website-jade.vercel.app/)'
2. Change theme to dark
3. Observe the like button colour in the cards

**Expected behavior**
In dark mode, Like button/icon color should be changed, such that it's visible in dark mode also.

**Screenshots**
<img width="212" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/0c149c2c-70e1-481e-ba96-1f88f841c5df">

**Comment by aishwarya-mali** [comment]
@baekusboo Can I work on this issue?

**Comment by real-coder007Ravi** [comment]
@baekusboo Could you please assign it to me

**Comment by Tanush-J** [comment]
what do think about this design for dark and light theme?

<img width="341" alt="image" src="https://github.com/baekusboo/music-website/assets/75922615/a558852d-a447-4238-8d5e-2c5702bee245">

<img width="397" style="border: 1px solid black;" alt="image" src="https://github.com/baekusboo/music-website/assets/75922615/694e23b2-5f50-4625-85dc-2fb958704682">

**Comment by baekusboo** [comment]
Looks fine @Tanush-J , Just now I have assigned this issue to @aishwarya-mali . So would you like to take up another issue and contribute to it?
