### ISSUE TITLE
fix: the sun-theme icon on dark mode

### ISSUE THREAD

**Issue by baekusboo** [baekusboo/music-website#105]
**Describe the bug**
The icon showed while changing themes is not changed properly. Only the moon icon is showed both in dark and light mode.

**To Reproduce**
1. Go to '[Music World Webpage](https://music-website-jade.vercel.app/)'
2. Change theme
3. Observe the theme icon

**BUG Screenshots**
In Dark mode
<img width="946" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/37af85b2-0b3b-482c-bd22-da6c23ffee91">
In Light mode
<img width="944" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/edd511ba-7029-4c88-a806-506ae34249ec">

**Expected behavior**
The theme icon should be sun in dark mode and moon in light mode as in below pics.

In Dark mode
<img width="943" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/b5b2d16c-d7c9-484a-bbd7-6841c36825c8">
In Light mode
<img width="946" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/0650fee0-5f1b-4cd3-9355-037e8f24cbad">

**Comment by saura8668** [comment]
hey @baekusboo can you please assign me this issue?

**Comment by baekusboo** [comment]
Sure, thanks for contributing to this issue @saura8668 ! Don't forget to link this issue number while raising a PR!

**Comment by saura8668** [comment]
Hey @baekusboo I've fixed the issue and made a pull request (#113). Please review.

**Comment by saura8668** [comment]
Hey @baekusboo If my pull request is fine can u please merge it or lable it as "hacktober fest accepted".

**Comment by baekusboo** [comment]
Yes, I am checking it. Give me few min, will merge yours under hacktoberfest!
