### ISSUE TITLE
fix: the searching of the search bar

### ISSUE THREAD

**Issue by baekusboo** [baekusboo/music-website#106]
**Describe the bug**
The search box filters the cards based on the username. It is case-sensitive.

**To Reproduce**
1. Go to '[Music World Webpage](https://music-website-jade.vercel.app/)'
2. Search name 'sai'
3. Observe that no card is visible

**Expected behavior**
The search bar should not be case-sensitive.

**Screenshots**
<img width="956" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/1e97ca74-3009-4074-98dd-a9de1c6ac4de">
<img width="946" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/53a68bdd-0090-4421-ac8c-713c47d37f3f">

**Comment by saura8668** [comment]
hey @baekusboo can you please assign me this issue?

**Comment by NipuniNuwanthika** [comment]
Hi, Please assign me this issuse.

**Comment by phaneendraandukuri** [comment]
Hi @baekusboo I have fixed this and raised a PR. Can you please have a look https://github.com/baekusboo/music-website/pull/118

**Comment by baekusboo** [comment]
Thanks for contributing @cricket-lover ! 

@saura8668 @NipuniNuwanthika thanks for contributing! Feel free to contribute on other issues of this project!
