### ISSUE TITLE
feat: Adding icon to get to the top of the webpage

### ISSUE THREAD

**Issue by baekusboo** [baekusboo/music-website#107]
**Is your feature request related to a problem? Please describe.**
Scrolling to the top of the website from the bottom is hard to do manually. It's hectic especially when there are more and more cards added to the webpage everyday!

**Describe the solution you'd like**
Adding some icon at the bottom of the webpage to get to top of the webpage instantly.

**Describe alternatives you've considered**
Maybe adding an arrow shaped icon would be better.

**Comment by baekusboo** [comment]
@NisooJadhav You can work on this issue.

**Comment by NisooJadhav** [comment]
@baekusboo 

https://github.com/baekusboo/music-website/assets/68807845/f088e195-9634-4f29-ac53-204e3ddf5896

can I open PR?

**Comment by baekusboo** [comment]
Looks great! It would be good if your PR has only the arrow feature. The theme icon fix is another issue. So I can't have your PR merged if it's linked to two issues at once.

**Comment by NisooJadhav** [comment]
@baekusboo done, I reverted the error that caused the Theme Icon Fix.

**Comment by NisooJadhav** [comment]
@baekusboo can you check #109 PR, if there is something wrong you can let me know, and I'll update it or make it from scratch again.
