### ISSUE TITLE
feat: Search icon should be inside the search field

### ISSUE THREAD

**Issue by Jyoti040** [baekusboo/music-website#111]
**Describe the bug**
The search icon is outside the search bar and doesn't look good . I want to place this icon in the search field so that UI of the website looks more good.

**Comment by Pritee668** [comment]
please assign this to me

**Comment by baekusboo** [comment]
Could you attach a screenshot @Jyoti040 and would you like to work on this issue or shall I assign it others?

**Comment by Jyoti040** [comment]
Yes I would like to work on it . 
![Screenshot_2023-10-19-11-26-40-989_com android chrome](https://github.com/baekusboo/music-website/assets/133634700/f147be57-e853-47b7-98ef-8919180a5cb3)

**Comment by Jyoti040** [comment]
Yes , would like to work on it .
Here is the screenshot of issue ,
![IMG_20231019_113041](https://github.com/baekusboo/music-website/assets/133634700/a242da63-9ba6-4280-9af7-7d714217ed9d)

**Comment by baekusboo** [comment]
@Jyoti040 Do contribute on this. Don't forget to link this issue number while opening the PR/MR. Happy Hacking! ^^

**Comment by baekusboo** [comment]
@Pritee-gupta-jpg Thanks for your interest, do check out the other open issues and contribute on that! Happy Hacking!

**Comment by baekusboo** [comment]
Hello @Pritee-gupta-jpg would you like to work on this issue?

**Comment by iamakhileshmishra** [comment]
@Jyoti040 @baekusboo could you assign this to me if this is still not solved/closed I would love to contribute on this, under hactoberfest tag

**Comment by baekusboo** [comment]
Hello @iamakhileshmishra  !
Thanks for your interest, I am assigning you this issue! Don't forget to link this issue number while opening the PR/MR. Happy Hacking! ^^

**Comment by iamakhileshmishra** [comment]
<img width="960" alt="image" src="https://github.com/baekusboo/music-website/assets/79476272/65ea98da-de1b-4591-a349-86ed095b0803">

Hello @baekusboo I hope i have solved the issue could you please check and confirm it. So that I could raise the PR ASAP.
:)

**Comment by iamakhileshmishra** [comment]
@baekusboo I have Raised the PR hope it solves your concern. :)
Please accept it under hacktoberfest-accepted tag

**Comment by baekusboo** [comment]
fixed in PR #163
