### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by Nupur19nj** [baekusboo/music-website#125]
Right now there is not back to top button user has to scroll all the way till top again which is kind of frustrating. 
Please assign me this task under hacktober-accepted!
![image](https://github.com/baekusboo/music-website/assets/114866308/01ec2710-3684-4efd-99c6-e8387b30630b)

**Comment by baekusboo** [comment]
@Nupur19nj This issue #107 is already present.

If you are interested, kindly look for another issue to work on! Happy Hacking! ^^
