### ISSUE TITLE
Fix : UI design of music card can be fixed

### ISSUE THREAD

**Issue by yube01** [baekusboo/music-website#134]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by baekusboo** [comment]
@yube01 Share me a description on how you will like to improve the UI of the cards. Please provide a suitable descriptions or screenshots for the same.

**Comment by yube01** [comment]
Text can be aligned in the centre for better user experience

Favourite song page can be added so that people can view the song which they have labelled as theirs favourite one

**Comment by baekusboo** [comment]
@yube01 The issues you have mentioned are already present. Check out issue #101 and the favorited songs are shown using the dropdown in the webpage. 

<img width="947" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/6018000f-a303-4a23-882f-c525a4390aff">
