### ISSUE TITLE
feat: I want to fix Toggle Theme logo, so it always stays in viewport

### ISSUE THREAD

**Issue by NisooJadhav** [baekusboo/music-website#141]
toggle theme logo position example:

https://github.com/baekusboo/music-website/assets/68807845/d3b62792-bb4d-4c06-a840-b7accb346dcf

@baekusboo can you please assign me this issue?

**Comment by baekusboo** [comment]
@NisooJadhav Don't change the font here! You can work on the floating theme icon! Also, don't forget to link this issue number to the PR raised.

**Comment by NisooJadhav** [comment]
sure

**Comment by NisooJadhav** [comment]
@baekusboo someone's PR has broken your logo, I don't have to fix this right?

![fault](https://github.com/baekusboo/music-website/assets/68807845/557297ac-8218-48dd-a91c-68e60004691c)

**Comment by baekusboo** [comment]
<img width="947" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/235b3cf2-a3cb-4fd8-b27e-521e01967552">

The site is working well at the production server. Hope there is no bug.

**Comment by NisooJadhav** [comment]
if you scroll it, then again go to top this is how it looks:

![fault](https://github.com/baekusboo/music-website/assets/68807845/8721a35c-d5a4-48db-ab38-37f33d571cb1)

I think let it be I will make my PR

**Comment by baekusboo** [comment]
![test - Made with Clipchamp](https://github.com/baekusboo/music-website/assets/83155556/b7002674-1610-444a-b250-87719eba04c3)

Well, I tried reproducing the bug, It still works fine at my end.

**Comment by NisooJadhav** [comment]
@baekusboo good to go then
