### ISSUE TITLE
feat: I want to add Local Storage based theme preference, so user will get the same theme he chose first.

### ISSUE THREAD

**Issue by NisooJadhav** [baekusboo/music-website#142]
example:

https://github.com/baekusboo/music-website/assets/68807845/f08ac1c2-ee7c-422a-99b6-fb4fe9552638

**Comment by Kinjal2004** [comment]
I want to work on this issue.

**Comment by NisooJadhav** [comment]
@Kinjal2004 sorry brother, the code is already written. I added many functionalities in one PR but repo owner wanted separate features in separate PR so, created multiple issues.

**Comment by baekusboo** [comment]
Proceed @NisooJadhav ! Thanks for your contributions! 

@Kinjal2004 do look for other issues to contribute! Happy Hacking!

**Comment by NisooJadhav** [comment]
@baekusboo thank you

**Comment by baekusboo** [comment]
Issue fixed in PR #153
