### ISSUE TITLE
Visibility Issues in dark mode

### ISSUE THREAD

**Issue by inviBeast** [baekusboo/music-website#150]
When we turn the theme to dark mode, visibility issues are in the card's bottom text. For your reference, I am attaching the screenshots. 
![hactoberfest23](https://github.com/baekusboo/music-website/assets/99094157/ae9a6a6b-2ace-4c9d-a734-a8e197c093a2)

**Comment by inviBeast** [comment]
I want to fix this issue as my contribution to Music World so please assign me this.

**Comment by baekusboo** [comment]
Hello @inviBeast , This is a duplicate issue, check out issue #103 and #104 ... You can look for other places to contribute! Thank you! Happy Hacking!
