### ISSUE TITLE
feat: Footer needs improvment

### ISSUE THREAD

**Issue by inviBeast** [baekusboo/music-website#151]
The footer is not properly made and it needs major enhancements.

![hactoberfest232](https://github.com/baekusboo/music-website/assets/99094157/4a9a2950-c003-451d-8101-b5e2abccab35)

**Comment by inviBeast** [comment]
I want to work on this issue.

**Comment by baekusboo** [comment]
Hello @inviBeast , you can work on this issue! Don't forget to link this issue no. while raising the PR!
