### ISSUE TITLE
Horizontal scroll during subtitle animation

### ISSUE THREAD

**Issue by RegimantasSimkus** [baekusboo/music-website#167]
**Describe the bug**

Horizontal scroll is present with subtitle animation
https://streamable.com/jprdgq

**To Reproduce**
1. Refresh page
2. Scroll sideways before the subtitle animation is complete

**Expected behavior**
No sideway scroll

**Screenshots**
![image](https://github.com/baekusboo/music-website/assets/91128330/9a5c1103-00ea-4b18-9ad9-0aca08eaf847)

**Additional context**

**Comment by baekusboo** [comment]
Closed by PR #160
