### ISSUE TITLE
I wish to change the heading Font and styling as its too basic

### ISSUE THREAD

**Issue by bilaljaved01** [baekusboo/music-website#19]
**Is your feature request related to a problem? Please describe.**
The idea is good but we can enhance the UI

We can make small changes here and there , for eg. use gradient color as background and style the heading

**Describe alternatives you've considered**
Rest seems good, very linear site so we should leave it be

**Comment by bilaljaved01** [comment]
Assign this to me under hacktoberfest

**Comment by baekusboo** [comment]
Proceed, don't forget to mention the issue number while raising the PR/MR! Happy Hacking! ^^

**Comment by mohitsaini07** [comment]
Hi @baekusboo, I would like to work on this issue. Can you assign it to me?

**Comment by baekusboo** [comment]
hello @mohitsaini07, you can also work on this issue. I will merge the best PR within three days - @bilaljaved01  @mohitsaini07 .

Also don't forget to mention the issue number while raising the PR/MR! Happy Hacking! ^^

**Comment by bilaljaved01** [comment]
> Hi @baekusboo, I would like to work on this issue. Can you assign it to me?

I have added the hover effect, one thing new contributor can do is make the text default color white whenever dark mode is turned on

**Comment by baekusboo** [comment]
@bilaljaved01 Kindly mention this issue number in the PR you worked on, so it will be closed once the change is merged..

**Comment by bilaljaved01** [comment]
I mentioned issue no. 19 in the pr

**Comment by anshul-132002** [comment]
@bilaljaved01 i want to contribute to this issue

**Comment by baekusboo** [comment]
@bilaljaved01 This issue was not linked with the PR. Please follow the format (fixes #ISSUE_NUMBER) in the PR description.

**Comment by bilaljaved01** [comment]
I did kindly check

**Comment by baekusboo** [comment]
Hello @anshul-132002 .. This issue has been assigned to two people already and it's almost fixed. Thanks for participating, do contribute in any other way you can to this project! Happy Hacking! ^^
