### ISSUE TITLE
Improvement in UI of song cards

### ISSUE THREAD

**Issue by harshverma2002** [baekusboo/music-website#23]
I want to enhance the UI of the song cards and make them look much more vibrant and less congested.
Please assign this issue to me under hacktoberfest 2023.

**Comment by baekusboo** [comment]
Proceed, don't forget to mention the issue number while raising the PR/MR! Happy Hacking! ^^

**Comment by mohitsaini07** [comment]
Hey @baekusboo, Is this the issue still available?

**Comment by baekusboo** [comment]
hello @mohitsaini07, you can also work on this issue. I will merge the best PR within three days - @harshverma2002 @mohitsaini07 .

Also don't forget to mention the issue number while raising the PR/MR! Happy Hacking! ^^

**Comment by anshul-132002** [comment]
@harshverma2002 i want to contribute to this issue

**Comment by baekusboo** [comment]
hello @anshul-132002, you can also work on this issue. I will merge the best PR within two days .

Also don't forget to mention the issue number in the PR description (fixes #ISSUE_NUMBER) while raising the PR/MR! Happy Hacking! ^^

**Comment by real-coder007Ravi** [comment]
@baekusboo ,Could you please assign it to me .
