### ISSUE TITLE
Want to Add text and improve UI so that users visiting the site are able to understand the purpose of the site. Could you please assign it under Hacktoberfest 2023 label.

### ISSUE THREAD

**Issue by real-coder007Ravi** [baekusboo/music-website#93]

**Comment by baekusboo** [comment]
Kindly give a brief description of the issue before raising the PR. Also, I would like you to create different issues for different errors. Avoid making all changes in one PR itself. Work on one issue at a time.

Kindly mention any one change you want to contribute in this issue to work on.

**Comment by Atheke** [comment]
I would like to suggest a suggest a spotify like theme for the website and i want to work on mainly the theme of the website changing the font and background colors

**Comment by baekusboo** [comment]
@Atheke raise a new feature request issue.

**Comment by baekusboo** [comment]
Closing issue as completed, PR #139
