### ISSUE TITLE
I want to add the Dark Mode animations, mouse cursor effects, card animations, and arrow at bottom to get to top, etc.

### ISSUE THREAD

**Issue by NisooJadhav** [baekusboo/music-website#94]

**Comment by baekusboo** [comment]
Kindly give a brief description of the issue before raising the PR. Also, I would like you to create different issues for different errors. Avoid making all changes in one PR itself. Work on one issue at a time.

Kindly mention any one change you want to contribute in this issue to work on.

**Comment by NisooJadhav** [comment]
I want to work on Card Animations, I can make a parallax sort of animation effect, so I created this site: https://hacker-newz.vercel.app/ you can see the effect when you scroll. I'm able to work on multiple features and contribute through 1 PR, but if I want one it would be this.

**Comment by baekusboo** [comment]
That looks cool! But I believe that makes the website a bit slow. If you could optimize on it in a better way, it's even better! 

Also, if you are interested, please work on the arrow feature at the bottom of the page as it might help to improve the webpage too.

**Comment by NisooJadhav** [comment]
@baekusboo It doesn't make the site slow at all in HackerNewz it is sending requests to two proxy servers which is why it appears slow, I have no problem in adding the arrow feature.

Please assign me that issue.

Thank you!

**Comment by baekusboo** [comment]
Fine, You can work on this parallax sort of animation effect on cards! It will be considered as a low priority feature for now.

Happy Hacking! ^^

**Comment by baekusboo** [comment]
@NisooJadhav shall I assign you to issue #107 ?

**Comment by NisooJadhav** [comment]
@baekusboo sure

**Comment by baekusboo** [comment]
Hello @NisooJadhav you can create a new issue to add your parallax effects on music cards and work on it if you would like to contribute more to this project.

Do raise new feature issues separately that you want to contribute on and raise PRs/MRs on it separately. Closing this issue as it has so many features listed at once.
