### ISSUE TITLE
I want to add the Footer Section to the site. 

### ISSUE THREAD

**Issue by real-coder007Ravi** [baekusboo/music-website#97]

**Comment by anshul-132002** [comment]
assign  me !

**Comment by real-coder007Ravi** [comment]
@baekusboo I have raised the issue.Could you please add it under HactoberFest 2023 label

**Comment by baekusboo** [comment]
@anshul-132002 & @real-coder007Ravi you can proceed working on this and I will merge the linked PR on first come first serve basis. Thanks for contributing!

**Comment by baekusboo** [comment]
Great Work! #hacktoberfest-accepted

Happy Hacking! ^^
