### ISSUE TITLE
fix: Align the cards in a row to center

### ISSUE THREAD

**Issue by baekusboo** [baekusboo/music-website#99]
**Describe the bug**
Cards are aligned towards the right of the webpage.

**To Reproduce**
1. Go to '[Music World Webpage](https://music-website-jade.vercel.app/)'
2. Scroll down

**Expected behavior**
Cards should be aligned towards the center.

**Screenshots**
<img width="960" alt="image" src="https://github.com/baekusboo/music-website/assets/83155556/21ed9c95-51a0-40b3-b5ff-2741e42defe9">

**Comment by real-coder007Ravi** [comment]
@baekusboo Could you please assign it to me

**Comment by baekusboo** [comment]
Assigned to you @real-coder007Ravi ! Thanks for taking up this issue!

**Comment by baekusboo** [comment]
@real-coder007Ravi any updates in fixing this issue?

**Comment by baekusboo** [comment]
Fixed by PR #136
